name: Formatter

on: [pull_request]

jobs:
  prettier:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prettify the code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: '--write .'
