name: Formatter

on: [pull_request]

jobs:
  prettier:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install dependencies
        run: npm ci
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
      # Workflows are not allowed to edit workflows. As result, we need to prevent Prettier from formatting them.
      - name: Prevent workflows from being formatted
        run: echo ".github" >> .prettierignore && cat .prettierignore
      - run: npm run fmt
      # Prevent the prettierignore change from being committed.
      - run: git checkout .prettierignore
      - uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # tag=v5
        with:
          commit_message: ':robot: Automated formatting fixes'
