#
# https://docs.npmjs.com/trusted-publishers
# https://docs.npmjs.com/staged-publishing
#

#GIT_COMMITTER_DATE="$(git show v4.13.0_DAISY --format=%aD | head -1)" git tag -a "v4.13.0-canary.1" v4.13.0_DAISY -m "release tag v4.13.0-canary.1" && git push --tags origin v4.13.0_DAISY && git --no-pager tag --list --format='%(refname)   %(taggerdate)'

#git tag -d v4.13.0-canary.1 && git push origin :refs/tags/v4.13.0-canary.1

name: Publish Package

#on:
#  release:
#    types: [published]

on:
  push:
    #branches: [v4.13.0_DAISY]
    tags:
      # https://github.com/daisy/ace/settings/rules
      - 'v*' # excludes slash /

# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  actions: none
  artifact-metadata: none
  attestations: none
  checks: none
  contents: none # <==========
  deployments: none
  discussions: none
  id-token: none # <==========
  issues: none
  models: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  publish:
    permissions:
      actions: none
      artifact-metadata: none
      attestations: none
      checks: none
      contents: read # <==========
      deployments: none
      discussions: none
      id-token: write # <========== Trusted Publishing OpenID Connect
      issues: none
      models: none
      packages: none
      pages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    #if: "github.event_name == 'push' && contains(github.event.head_commit.message, 'release tag')"
    #if: "contains(github.event.head_commit.message, 'release tag')"
    if: "github.event_name != 'pull_request' && github.ref_name == 'v4.13.0_DAISY' && github.repository_owner == 'daisy'"
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    env:
      DISPLAY: :99
    steps:
# https://github.com/actions/checkout/commits/v7.0.1
# https://github.com/actions/checkout/commits/3d3c42e5aac5ba805825da76410c181273ba90b1
# https://github.com/actions/checkout/compare/v7.0.1...3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
# https://github.com/actions/setup-node/commits/v7.0.0
# https://github.com/actions/setup-node/commits/820762786026740c76f36085b0efc47a31fe5020
# https://github.com/actions/setup-node/compare/v7.0.0...820762786026740c76f36085b0efc47a31fe5020
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
# https://github.com/actions/setup-node#caching-global-packages-data
# https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
# https://github.com/actions/cache/blob/main/examples.md#node---npm
# https://github.com/actions/setup-node/issues/1553#issuecomment-4750595425
        with:
          node-version: '26'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
          cache: ''
#        cache: 'npm'
#        node-version-file: package.json
#        package-manager-cache: true
#        cache-dependency-path: 'package-lock.json'
        #check-latest: true
      - run: node --version ; npm --version
      - run: npm --global install npm@^12
      - run: npm --version
      - run: npm --global --ignore-scripts --foreground-scripts install sfw
      - run: sfw --version
      - run: npm --global install pnpm@^11
      - run: pnpm --version
      - name: (P)NPM INSTALL
        # ; (npm audit || echo OK) ; (npm outdated || echo OK) ; ((pnpm exec --no --offline -- taze --maturity-period 3 --fail-on-outdated --all --force --include-locked --concurrency 1 --loglevel debug --cwd . && pnpm exec --no --offline -- taze --maturity-period 3 major --fail-on-outdated --all --force --include-locked --concurrency 1 --loglevel debug --cwd .) || echo OK)
        run: rm -rf node_modules ; HUSKY=0 HUSKY_SKIP_HOOKS=0 HUSKY_SKIP_INSTALL=0 sfw pnpm ci --frozen-lockfile
        shell: bash
      - name: BUILD
        run: pnpm run build
        shell: bash
      # - &install-deps-with-xvfb
      #   name: Install Deps
      #   uses: ./.github/actions/install-deps
      #   id: install-deps
      #   with:
      #     start-xvfb: ${{ env.DISPLAY }}
      # - name: CHROME TESTS
      #   env:
      #     CHROME_BIN: ${{ steps.install-deps.outputs.chrome-path }}
      #     CHROMEDRIVER_BIN: ${{ steps.install-deps.outputs.chromedriver-path }}
      #   run: env | grep -i CHROME ; WTR_BROWSER=chrome pnpm run test:integration:chrome ; WTR_BROWSER=chrome pnpm run test
      # - name: HUSKY
      #   run: (npx husky || echo OK)
      #   shell: bash
      # - name: CHROME TESTS
      #   run: rm -rf ~/.browser-driver-manager ; npx browser-driver-manager install chromedriver --verbose ; cat ~/.browser-driver-manager/.env ; source ~/.browser-driver-manager/.env ; env | grep -i CHROME ; echo $CHROME_TEST_PATH ; export CHROME_BIN="${CHROME_TEST_PATH}" ; echo $CHROMEDRIVER_TEST_PATH ; export CHROMEDRIVER_BIN="${CHROMEDRIVER_TEST_PATH}" ; npm run test:chromeheadless
      #   shell: bash
      - name: PACKAGE PUBLISH
        #env:
        #  NPM_CONFIG_PROVENANCE: true
        shell: bash
        run: npm stage publish --access public --tag=latest .

#TECHNICAL NOTE: IT IS POSSIBLE TO RETRIVEVE NPM_TOKEN VIA AN OPENIDCONNECT ENDPOINT (DO NOT DO THIS!)
#OIDC_TOKEN=$(curl -sH "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=npm:registry.npmjs.org" | jq -r .value)
#NPM_TOKEN=$(curl -s -X POST https://registry.npmjs.org/-/npm/v1/oidc/token/exchange/package/%40daisy%2Faxe-core-for-ace -H "Content-Type: application/json" -H "Authorization: Bearer $OIDC_TOKEN" -d "{\"oidcToken\":\"$OIDC_TOKEN\"}" | jq -r .token)
#THIS LEAKS THE SECRET IN LOGS: echo $NPM_TOKEN | base64 -w 0 | base64 -w 0
#npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
#npm publish...
